name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Get latest Vine commit SHA
      id: vine-sha
      run: |
        echo "sha=$(git ls-remote https://github.com/VineLang/vine main | cut -f1)" >> $GITHUB_OUTPUT
    - name: Cache vine-cli
      id: vine-cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/vine
        key: vine-cli-${{ steps.vine-sha.outputs.sha }}
    - name: Install vine-cli if not cached
      if: steps.vine-cache.outputs.cache-hit != 'true'
      run: cargo install vine-cli --git https://github.com/VineLang/vine --rev ${{ steps.vine-sha.outputs.sha }}

    - name: Run tests
      run: |
        python tests/run_tests.py